package it.unipi.movieland.model.Enum;

public enum CountryEnum {
    AF("Afghanistan"),
    AL("Albania"),
    DZ("Algeria"),
    AD("Andorra"),
    AO("Angola"),
    AG("Antigua and Barbuda"),
    AR("Argentina"),
    AM("Armenia"),
    AU("Australia"),
    AT("Austria"),
    AZ("Azerbaijan"),
    BS("Bahamas"),
    BH("Bahrain"),
    BD("Bangladesh"),
    BB("Barbados"),
    BY("Belarus"),
    BE("Belgium"),
    BZ("Belize"),
    BJ("Benin"),
    BT("Bhutan"),
    BO("Bolivia"),
    BA("Bosnia and Herzegovina"),
    BW("Botswana"),
    BR("Brazil"),
    BN("Brunei"),
    BG("Bulgaria"),
    BF("Burkina Faso"),
    BI("Burundi"),
    KH("Cambodia"),
    CM("Cameroon"),
    CA("Canada"),
    CV("Cape Verde"),
    CF("Central African Republic"),
    TD("Chad"),
    CL("Chile"),
    CN("China"),
    CO("Colombia"),
    KM("Comoros"),
    CG("Congo"),
    CR("Costa Rica"),
    HR("Croatia"),
    CU("Cuba"),
    CY("Cyprus"),
    CZ("Czech Republic"),
    DK("Denmark"),
    DJ("Djibouti"),
    DM("Dominica"),
    DO("Dominican Republic"),
    EC("Ecuador"),
    EG("Egypt"),
    SV("El Salvador"),
    GQ("Equatorial Guinea"),
    ER("Eritrea"),
    EE("Estonia"),
    SZ("Eswatini"),
    ET("Ethiopia"),
    FJ("Fiji"),
    FI("Finland"),
    FR("France"),
    GA("Gabon"),
    GM("Gambia"),
    GE("Georgia"),
    DE("Germany"),
    GH("Ghana"),
    GR("Greece"),
    GD("Grenada"),
    GT("Guatemala"),
    GN("Guinea"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HT("Haiti"),
    HN("Honduras"),
    HU("Hungary"),
    IS("Iceland"),
    IN("India"),
    ID("Indonesia"),
    IR("Iran"),
    IQ("Iraq"),
    IE("Ireland"),
    IL("Israel"),
    IT("Italy"),
    JM("Jamaica"),
    JP("Japan"),
    JO("Jordan"),
    KZ("Kazakhstan"),
    KE("Kenya"),
    KI("Kiribati"),
    KW("Kuwait"),
    KG("Kyrgyzstan"),
    LA("Laos"),
    LV("Latvia"),
    LB("Lebanon"),
    LS("Lesotho"),
    LR("Liberia"),
    LY("Libya"),
    LI("Liechtenstein"),
    LT("Lithuania"),
    LU("Luxembourg"),
    MG("Madagascar"),
    MW("Malawi"),
    MY("Malaysia"),
    MV("Maldives"),
    ML("Mali"),
    MT("Malta"),
    MX("Mexico"),
    MD("Moldova"),
    MC("Monaco"),
    MN("Mongolia"),
    ME("Montenegro"),
    MA("Morocco"),
    MZ("Mozambique"),
    MM("Myanmar"),
    NA("Namibia"),
    NP("Nepal"),
    NL("Netherlands"),
    NZ("New Zealand"),
    NI("Nicaragua"),
    NE("Niger"),
    NG("Nigeria"),
    KP("North Korea"),
    NO("Norway"),
    OM("Oman"),
    PK("Pakistan"),
    PA("Panama"),
    PY("Paraguay"),
    PE("Peru"),
    PH("Philippines"),
    PL("Poland"),
    PT("Portugal"),
    QA("Qatar"),
    RO("Romania"),
    RU("Russia"),
    SA("Saudi Arabia"),
    SN("Senegal"),
    RS("Serbia"),
    SG("Singapore"),
    SK("Slovakia"),
    SI("Slovenia"),
    ZA("South Africa"),
    KR("South Korea"),
    ES("Spain"),
    LK("Sri Lanka"),
    SE("Sweden"),
    CH("Switzerland"),
    TH("Thailand"),
    TR("Turkey"),
    UA("Ukraine"),
    AE("United Arab Emirates"),
    GB("United Kingdom"),
    US("United States"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    VN("Vietnam"),
    YE("Yemen"),
    ZM("Zambia"),
    ZW("Zimbabwe");

    private final String countryName;

    CountryEnum(String countryName) {
        this.countryName = countryName;
    }

    public String getCountryName() {
        return countryName;
    }
}
